# Generated by Django 4.1.2 on 2025-04-23 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deuldou', '0014_listecontacts_delete_liste_contacts_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='contact unique',
        ),
        migrations.AlterField(
            model_name='listecontacts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_listes_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
